In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 
import numpy as np
import pandas as pd
import sys
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
import random
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import shutil

sys.path.append('../')
from meta_fusion.benchmarks import *
from meta_fusion.methods import *
from meta_fusion.models import *
from meta_fusion.utils import *
from meta_fusion.third_party import *
from meta_fusion.synthetic_data import PrepareSyntheticData
from meta_fusion.config import *
from meta_fusion.methodsextra import *
from meta_fusion.methodsextra_new import *

ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

In [ ]:
#########################
# Experiment parameters #
#########################
if True:
    # Parse input arguments
    print ('Number of arguments:', len(sys.argv), 'arguments.')
    print ('Argument List:', str(sys.argv))
    if len(sys.argv) != 2:
        print("Error: incorrect number of parameters.")
        quit()

    seed = 1234
    print(seed)

# Fixed data parameters
repetition=1

# Data model parameters
n = 2000
dim_modalities = [200, 300, 100]
# dim_modalities = [100, 150, 50]

dim_latent = [20, 30, 10, 0] # last one is the shared component 
# noise_ratios = [0.6, 0.1, 0.1, 0, 0, 0.9] # 19 March:Correlation pairwise/correlation with the output, if y >0, more missing

noise_ratios = [0.6, 0.1, 0.1]
# noise_ratios = [0.2, 0.2, 0.2]

trans_type = ["linear", "quadratic", "quadratic", "linear"] #last one is shared
# trans_type = ["quadratic", "quadratic", "quadratic", "quadratic"] # New: last one is shared, change to quadratic

mod_prop = [1, 1, 1, 0, 0]
interactive_prop = 0

missing_value = 100.0
fractions = [0.95, 0.5, 0.5] # presence percentages

# mod_outs = [[0, 200, 300, 400, 500], [0, 100, 200, 300, 400]]
# mod_outs = [[0, 500], [0, 400]]
num_modalities = len(dim_modalities)
print('num_modalities', num_modalities)
combined_hiddens = [128, 64] # only used for benchmarks
mod_hiddens = [[256], [256], [256]] # hidden layer for each modality

# data parameters
data_name = 'regression'
exp_name = data_name + "_" + "linear_early"
output_dim = 1  # specify the output dimension for regression


extractor_type = 'separate'
separate=True
is_mod_static=[False]*num_modalities
freeze_mod_extractors=[False]*num_modalities

# Load default model configurations 
config = load_config('../experiments_synthetic/config.json')
extractor_config = load_config('../experiments_synthetic/config_extractor.json')

# Model files directory
ckpt_dir = f"./checkpoints/{exp_name}/seed{seed}/"
config['ckpt_dir'] = extractor_config['ckpt_dir'] = ckpt_dir

# Update other training parameters
config['output_dim'] = extractor_config['output_dim'] = output_dim
config["init_lr"] = 0.001
config["ensemble_methods"] = [
        "simple_average",
        "weighted_average",
        # "meta_learner",
        "greedy_ensemble"
        ]
extractor_config["init_lr"] = [0.001] * num_modalities
extractor_config["weight_decay"] = [0] * num_modalities

#####################
#    Load Dataset   #
#####################
data_preparer = PrepareSyntheticData(data_name = data_name, test_size = 0.2, val_size = 0.2)
print(f"Finished generating {exp_name} dataset.")
sys.stdout.flush() 


###############
# Output file #
###############
# NOTE: set this to "imputation" (missing modalities kept, trainer handles missing)
# or "filtered" (only fully-observed samples kept)
# EXPERIMENT_VARIANT = "imputation"
EXPERIMENT_VARIANT = "filtered"


# Fractions (presence percentages) used for missingness experiments
fractions = [1, 0.8, 0.6]

outdir = f"./results/{exp_name}/"
os.makedirs(outdir, exist_ok=True)

# Derive a compact transform label (e.g., "linear" or "quadratic").
# If not all transforms are the same, encode them in order as m1_.._mK_.._shared_..
if len(set(trans_type)) == 1:
    trans_label = trans_type[0]
else:
    # trans_type is expected to be length (num_modalities + 1) where last entry is shared
    per_mod = [f"m{i+1}{t}" for i, t in enumerate(trans_type[:num_modalities])]
    shared = f"shared{trans_type[num_modalities]}" if len(trans_type) > num_modalities else "shared?"
    trans_label = "_".join(per_mod + [shared])


# Header for results file
def add_header(results):
    results['extractor']=extractor_type
    results['weight_type'] = config['divergence_weight_type'] 
    return results

Number of arguments: 2 arguments.
Argument List: ['/opt/anaconda3/envs/fusion_stable310/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/parnian/Library/Jupyter/runtime/kernel-v3e24b4b445fe2ccd64eae285e4452fab757c3b2a5.json']
1234
num_modalities 3
Finished generating regression_linear_early dataset.

In [ ]:
#----------------#
# Split dataset  #
#----------------#
missing_value = 10.0
train_loader, val_loader, test_loader, oracle_train_loader, oracle_val_loader, oracle_test_loader =\
data_preparer.get_data_loaders(n, trans_type=trans_type, mod_prop=mod_prop, 
                                interactive_prop = interactive_prop,
                                dim_modalities=dim_modalities, dim_latent=dim_latent,
                                noise_ratios=noise_ratios, random_state=1234)
fractions = [1, 0.8, 0.6] # presence percentages
train_miss, val_miss, test_miss = data_preparer.apply_missing_modalities(
    train_loader, val_loader, test_loader, modality_fractions=fractions, random_state=0,
    missing_value=missing_value
)                     ### based on presence fraction of each modality, randomly mask some values to missing_value.          
train_all_modalities, val_all_modalities, test_all_modalities = data_preparer.filter_fully_observed(
    train_miss, val_miss, test_miss, missing_value=missing_value
)  #### Only keep the datapoints that have all modalities present.

In [4]:
*modalities, y = train_loader.dataset[0]
print(len(modalities), len(modalities[0]), len(modalities[1]), len(modalities[2]), y)

3 500 400 100 tensor([-9.2496])

In [5]:
meta_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens = mod_hiddens, output_dim=output_dim)

In [13]:
cohort_models = meta_cohort.get_cohort_models()
_, dim_pairs = meta_cohort.get_cohort_info()
print(cohort_models, dim_pairs)

[MLP_Net(
  (model): Sequential(
    (0): Linear(in_features=500, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=1, bias=True)
  )
), MLP_Net(
  (model): Sequential(
    (0): Linear(in_features=400, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=1, bias=True)
  )
), MLP_Net(
  (model): Sequential(
    (0): Linear(in_features=100, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=1, bias=True)
  )
)] [500, 400, 100]

In [16]:
jointmodel = Trainer_Joint_new(config, cohort_models, [train_miss, val_miss]) # New trainer function. 
jointmodel.train('marginal', missing_value=missing_value) 
res = jointmodel.test(test_miss, missing_value=missing_value)

Start training student cohort...

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 1903.75it/s, loss=18.4219, batch_time=0.034s]

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2289.00it/s, loss=16.7726, batch_time=0.028s]

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2217.05it/s, loss=14.7758, batch_time=0.029s]

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2144.79it/s, loss=13.1015, batch_time=0.030s]

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 1836.74it/s, loss=12.4520, batch_time=0.035s]

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2275.83it/s, loss=11.2229, batch_time=0.028s]

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2253.64it/s, loss=9.5362, batch_time=0.028s]

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2230.20it/s, loss=9.7074, batch_time=0.029s]

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2266.16it/s, loss=8.0498, batch_time=0.028s]

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2030.10it/s, loss=7.0537, batch_time=0.032s]

Finished training student cohort!
Training meta learner on the best cohort...

1280it [00:00, 5318.23it/s]

meta_learner: train task loss: 199.474 - val task loss: 132.780 [*] Best so far

1280it [00:00, 5141.28it/s]

meta_learner: train task loss: 132.395 - val task loss: 118.730 [*] Best so far

1280it [00:00, 5512.71it/s]

meta_learner: train task loss: 101.472 - val task loss: 100.458 [*] Best so far

1280it [00:00, 5238.24it/s]

meta_learner: train task loss: 94.332 - val task loss: 102.014

1280it [00:00, 5938.79it/s]

meta_learner: train task loss: 93.141 - val task loss: 112.875

1280it [00:00, 5930.07it/s]

meta_learner: train task loss: 90.825 - val task loss: 106.773

1280it [00:00, 5879.33it/s]

meta_learner: train task loss: 74.570 - val task loss: 97.598 [*] Best so far

1280it [00:00, 5922.01it/s]

meta_learner: train task loss: 57.487 - val task loss: 91.165 [*] Best so far

1280it [00:00, 5908.19it/s]

meta_learner: train task loss: 55.852 - val task loss: 83.567 [*] Best so far

1280it [00:00, 5836.96it/s]

meta_learner: train task loss: 52.745 - val task loss: 82.635 [*] Best so far
Done!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [0, 1] with losses: [tensor(184.4302, grad_fn=<MseLossBackward0>), tensor(3500.3726, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 58.96955490112305
Method: (weighted_average), Test_MSE: 61.7009391784668
Method: (meta_learner), Test_MSE: 74.01079559326172
Method: (greedy_ensemble), Test_MSE: 92.37108612060547
Method: (best_single), Test_MSE: 190.04820251464844
Method: (cohort), Test_MSE: [190.04820251464844, 272.7131042480469, 205.59217834472656]

In [14]:
### With imputation of missing values.

In [3]:
#####################
# Define Experiment #
#####################
def run_single_experiment(config, extractor_config, n, random_state, mod_hiddens,
                          run_oracle=False, run_coop=True, run_all_at_once=False):


    config['random_state'] = random_state
    extractor_config['random_state'] = random_state
    res_list = []
    best_rho = {}
    cohort_pairs = {}
    ens_idxs = {}
    cluster_idxs = {}


    #----------------#
    # Split dataset  #
    #----------------#
    train_loader, val_loader, test_loader, oracle_train_loader, oracle_val_loader, oracle_test_loader =\
    data_preparer.get_data_loaders(n, trans_type=trans_type, mod_prop=mod_prop, 
                                    interactive_prop = interactive_prop,
                                    dim_modalities=dim_modalities, dim_latent=dim_latent,
                                    noise_ratios=noise_ratios, random_state=random_state)
    # Get data info

    # fractions = [1.0, 1.0, 1.0] # presence percentages
    train_loader, val_loader, test_loader = data_preparer.apply_missing_modalities(
        train_loader, val_loader, test_loader, modality_fractions=fractions, random_state=0,
        missing_value=missing_value
    )                     ### based on presence fraction of each modality, randomly mask some values to missing_value.          

    n_train = len(train_loader.dataset)
    n_val = len(val_loader.dataset)
    n_test = len(test_loader.dataset)
    n = n_train + n_val + n_test

    print(f"Finished splitting {data_name} dataset. Data information are summarized below:\n"
            f"Modality dimensions: {dim_modalities}\n"
            f"Data size: {n}\n"
            f"Train size: {n_train}\n"
            f"Val size: {n_val}\n"
            f"Test size: {n_test}")
    sys.stdout.flush() 

    #------------------#
    # Benchmark models #
    #------------------#
    bm_extractor = Extractors([[d,0] for d in dim_modalities], dim_modalities, train_loader, val_loader)
    _ = bm_extractor.get_dummy_extractors()
    bm_cohort = Cohorts(extractors=bm_extractor, combined_hidden_layers=combined_hiddens, output_dim=output_dim)
    meta_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)
    bm_models = bm_cohort.get_cohort_models()
    _, bm_dims = bm_cohort.get_cohort_info()
    bm = Benchmarks(config, bm_models, bm_dims, [train_loader, val_loader])
    bm.train()
    res = bm.test(test_loader)
    res_list.append(res)
    print(f"Finished running basic benchmarks!")

    #------------------------------#
    #  Train and test Meta Fuse    #
    #------------------------------#
    cohort_models = meta_cohort.get_cohort_models()
    _, dim_pairs = meta_cohort.get_cohort_info()
    ###### Only change the two following.
    metafuse = Trainer_new(config, cohort_models, [train_loader, val_loader]) # New trainer function. 
    metafuse.train() 
    res = metafuse.test(test_loader) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"metafusion_{k}": v for k, v in res.items()}
    res_list.append(res)
    metafuse.train_ablation() # This is just late fusion with student cohort.
    res = metafuse.test_ablation(test_loader) # I don't need this, no need to have different rhos.
    res = {f"indep_{k}": v for k, v in res.items()}
    res_list.append(res)

    best_rho['metafusion'] = metafuse.best_rho
    cohort_pairs['metafusion'] = dim_pairs
    cohort_pairs['indep'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['metafusion_greedy_ensemble'] = metafuse.ens_idxs  

    if config['divergence_weight_type'] == "clustering":
        cluster_idxs['metafusion'] = metafuse.cluster_idxs

    print(f"Finished running meta fusion!")


    #----------------------------#
    # Proposed model: Joint train#
    #----------------------------#
    joint_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)

    # ------------------------------#
    #  Train and test Joint train  #
    # ------------------------------#
    cohort_models = joint_cohort.get_cohort_models()
    _, dim_pairs = joint_cohort.get_cohort_info()
    ###### Only change the two following.
    jointmodel = Trainer_Joint_new(config, cohort_models, [train_loader, val_loader]) # New trainer function. 
    jointmodel.train('marginal', missing_value=missing_value) 
    res = jointmodel.test(test_loader, missing_value=missing_value) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"jointlearning_{k}": v for k, v in res.items()}
    res_list.append(res)
    cohort_pairs['cohort'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['jointlearning_greedy_ensemble'] = jointmodel.ens_idxs  


    print(f"Finished running joint fusion!")


    #----------------------------#
    # Proposed model: Shapley train#
    #----------------------------#

    joint_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)

    #------------------------------#
    #  Train and test shapley train  #
    #------------------------------#
    cohort_models = joint_cohort.get_cohort_models()
    _, dim_pairs = joint_cohort.get_cohort_info()
    ###### Only change the two following.
    jointmodel = Trainer_Joint_new(config, cohort_models, [train_loader, val_loader]) # New trainer function. 
    jointmodel.train('shapley', missing_value=missing_value) 
    res = jointmodel.test(test_loader,missing_value=missing_value) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"shapley_{k}": v for k, v in res.items()}
    res_list.append(res)
    cohort_pairs['cohort'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['shapley_greedy_ensemble'] = jointmodel.ens_idxs  


    print(f"Finished running shapley fusion!")        

    results = []
    for i, res in enumerate(res_list):
        for method, val in res.items():
            results.append({'Method': method, 'Test_metric': val, 
                            'best_rho':best_rho.get(method.split('_')[0]), 'cohort_pairs':cohort_pairs.get(method.split('_')[0]),
                            'ensemble_idxs': ens_idxs.get(method), 'cluster_idxs': cluster_idxs.get(method.split('_')[0])})

    results = pd.DataFrame(results)
    results['random_state']=random_state
    results["dim_modalities"] = [dim_modalities] * len(results)
    results['n'] = n
    results['n_train'] = n_train
    results['n_val'] = n_val
    results['n_test'] = n_test 

    return results

In [4]:
#####################
#  Run Experiments  #
#####################
results = []

for i in tqdm(range(1, repetition+1), desc="Repetitions", leave=True, position=0):
    print(f'Running with repetition {i}...')
    random_state = repetition * (seed-1) + i
    # print(random_state)
    set_random_seed(random_state)

    # Run experiment
    tmp = run_single_experiment(config, extractor_config, n, random_state, mod_hiddens,
                                run_oracle=False, run_coop=True, run_all_at_once=False)
    
    results.append(tmp)


results = pd.concat(results, ignore_index=True)

add_header(results)

Repetitions:   0%|          | 0/1 [00:00<?, ?it/s]

Running with repetition 1...
Finished splitting regression dataset. Data information are summarized below:
Modality dimensions: [200, 300, 100]
Data size: 2000
Train size: 1280
Val size: 320
Test size: 400

/Users/parnian/Desktop/Github/Multimodal-ML/notebooks/../meta_fusion/utils.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.data = torch.tensor(data, dtype=torch.float32)

Start training benchmark models...
Training with disagreement penalty = 0

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2824.58it/s]

model_1: train loss: 493.529, train task loss: 493.529 - val loss: 438.200, val task loss: 438.200 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/0
model_2: train loss: 495.612, train task loss: 495.612 - val loss: 432.088, val task loss: 432.088 [*] Best so far
model_3: train loss: 474.116, train task loss: 474.116 - val loss: 436.282, val task loss: 436.282 [*] Best so far
model_4: train loss: 488.675, train task loss: 488.675 - val loss: 440.101, val task loss: 440.101 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3457.39it/s]

model_1: train loss: 469.620, train task loss: 469.620 - val loss: 411.535, val task loss: 411.535 [*] Best so far
model_2: train loss: 472.547, train task loss: 472.547 - val loss: 413.504, val task loss: 413.504 [*] Best so far
model_3: train loss: 461.938, train task loss: 461.938 - val loss: 424.356, val task loss: 424.356 [*] Best so far
model_4: train loss: 462.266, train task loss: 462.266 - val loss: 427.978, val task loss: 427.978 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3351.12it/s]

model_1: train loss: 417.113, train task loss: 417.113 - val loss: 385.693, val task loss: 385.693 [*] Best so far
model_2: train loss: 431.885, train task loss: 431.885 - val loss: 398.920, val task loss: 398.920 [*] Best so far
model_3: train loss: 433.483, train task loss: 433.483 - val loss: 409.809, val task loss: 409.809 [*] Best so far
model_4: train loss: 444.670, train task loss: 444.670 - val loss: 414.217, val task loss: 414.217 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3304.12it/s]

model_1: train loss: 380.654, train task loss: 380.654 - val loss: 390.261, val task loss: 390.261
model_2: train loss: 391.604, train task loss: 391.604 - val loss: 388.281, val task loss: 388.281 [*] Best so far
model_3: train loss: 409.223, train task loss: 409.223 - val loss: 409.393, val task loss: 409.393 [*] Best so far
model_4: train loss: 407.442, train task loss: 407.442 - val loss: 379.575, val task loss: 379.575 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3252.99it/s]

model_1: train loss: 361.127, train task loss: 361.127 - val loss: 393.831, val task loss: 393.831
model_2: train loss: 385.011, train task loss: 385.011 - val loss: 378.990, val task loss: 378.990 [*] Best so far
model_3: train loss: 396.661, train task loss: 396.661 - val loss: 412.739, val task loss: 412.739
model_4: train loss: 370.791, train task loss: 370.791 - val loss: 389.721, val task loss: 389.721

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3311.75it/s]

model_1: train loss: 345.055, train task loss: 345.055 - val loss: 398.424, val task loss: 398.424
model_2: train loss: 367.506, train task loss: 367.506 - val loss: 374.011, val task loss: 374.011 [*] Best so far
model_3: train loss: 396.475, train task loss: 396.475 - val loss: 430.998, val task loss: 430.998
model_4: train loss: 359.607, train task loss: 359.607 - val loss: 368.994, val task loss: 368.994 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3242.83it/s]

model_1: train loss: 325.368, train task loss: 325.368 - val loss: 405.397, val task loss: 405.397
model_2: train loss: 353.953, train task loss: 353.953 - val loss: 380.094, val task loss: 380.094
model_3: train loss: 389.690, train task loss: 389.690 - val loss: 412.572, val task loss: 412.572
model_4: train loss: 334.941, train task loss: 334.941 - val loss: 356.908, val task loss: 356.908 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3432.56it/s]

model_1: train loss: 304.878, train task loss: 304.878 - val loss: 414.309, val task loss: 414.309
model_2: train loss: 349.791, train task loss: 349.791 - val loss: 363.573, val task loss: 363.573 [*] Best so far
model_3: train loss: 380.264, train task loss: 380.264 - val loss: 409.791, val task loss: 409.791
model_4: train loss: 314.746, train task loss: 314.746 - val loss: 359.252, val task loss: 359.252

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3398.50it/s]

model_1: train loss: 280.326, train task loss: 280.326 - val loss: 423.058, val task loss: 423.058
model_2: train loss: 333.252, train task loss: 333.252 - val loss: 366.235, val task loss: 366.235
model_3: train loss: 374.990, train task loss: 374.990 - val loss: 407.037, val task loss: 407.037 [*] Best so far
model_4: train loss: 302.659, train task loss: 302.659 - val loss: 386.059, val task loss: 386.059

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3442.43it/s]

model_1: train loss: 253.909, train task loss: 253.909 - val loss: 441.436, val task loss: 441.436
model_2: train loss: 318.972, train task loss: 318.972 - val loss: 358.623, val task loss: 358.623 [*] Best so far
model_3: train loss: 374.594, train task loss: 374.594 - val loss: 400.742, val task loss: 400.742 [*] Best so far
model_4: train loss: 294.881, train task loss: 294.881 - val loss: 358.767, val task loss: 358.767
Finished training benchmark models!
Method: (modality_1), Test_MSE: 359.3453063964844
Method: (modality_2), Test_MSE: 332.8011779785156
Method: (modality_3), Test_MSE: 360.9461975097656
Method: (early_fusion), Test_MSE: 315.76202392578125
Method: (late_fusion), Test_MSE: 312.86676025390625
Finished running basic benchmarks!
Start training student cohort...
Training with disagreement penalty = 0

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5351.48it/s]

model_1: train loss: 494.186, train task loss: 494.186 - val loss: 436.359, val task loss: 436.359 [*] Best so far
model_2: train loss: 638.088, train task loss: 638.088 - val loss: 428.957, val task loss: 428.957 [*] Best so far
model_3: train loss: 610.673, train task loss: 610.673 - val loss: 432.122, val task loss: 432.122 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5422.16it/s]

model_1: train loss: 469.928, train task loss: 469.928 - val loss: 419.909, val task loss: 419.909 [*] Best so far
model_2: train loss: 468.403, train task loss: 468.403 - val loss: 444.328, val task loss: 444.328
model_3: train loss: 478.248, train task loss: 478.248 - val loss: 428.656, val task loss: 428.656 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5359.13it/s]

model_1: train loss: 440.827, train task loss: 440.827 - val loss: 402.203, val task loss: 402.203 [*] Best so far
model_2: train loss: 459.057, train task loss: 459.057 - val loss: 444.285, val task loss: 444.285
model_3: train loss: 442.932, train task loss: 442.932 - val loss: 408.734, val task loss: 408.734 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 4938.88it/s]

model_1: train loss: 410.878, train task loss: 410.878 - val loss: 387.282, val task loss: 387.282 [*] Best so far
model_2: train loss: 429.878, train task loss: 429.878 - val loss: 384.815, val task loss: 384.815 [*] Best so far
model_3: train loss: 425.582, train task loss: 425.582 - val loss: 439.442, val task loss: 439.442

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5345.05it/s]

model_1: train loss: 384.343, train task loss: 384.343 - val loss: 383.238, val task loss: 383.238 [*] Best so far
model_2: train loss: 429.356, train task loss: 429.356 - val loss: 379.864, val task loss: 379.864 [*] Best so far
model_3: train loss: 404.015, train task loss: 404.015 - val loss: 439.628, val task loss: 439.628

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 4370.41it/s]

model_1: train loss: 367.529, train task loss: 367.529 - val loss: 385.444, val task loss: 385.444
model_2: train loss: 388.114, train task loss: 388.114 - val loss: 374.918, val task loss: 374.918 [*] Best so far
model_3: train loss: 417.141, train task loss: 417.141 - val loss: 419.836, val task loss: 419.836

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5225.62it/s]

model_1: train loss: 353.248, train task loss: 353.248 - val loss: 388.013, val task loss: 388.013
model_2: train loss: 381.951, train task loss: 381.951 - val loss: 427.692, val task loss: 427.692
model_3: train loss: 406.351, train task loss: 406.351 - val loss: 399.473, val task loss: 399.473 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5392.34it/s]

model_1: train loss: 340.020, train task loss: 340.020 - val loss: 391.774, val task loss: 391.774
model_2: train loss: 397.537, train task loss: 397.537 - val loss: 387.848, val task loss: 387.848
model_3: train loss: 385.735, train task loss: 385.735 - val loss: 430.099, val task loss: 430.099

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 4966.07it/s]

model_1: train loss: 326.769, train task loss: 326.769 - val loss: 395.062, val task loss: 395.062
model_2: train loss: 354.921, train task loss: 354.921 - val loss: 395.566, val task loss: 395.566
model_3: train loss: 397.506, train task loss: 397.506 - val loss: 398.207, val task loss: 398.207 [*] Best so far

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 5311.51it/s]

model_1: train loss: 312.946, train task loss: 312.946 - val loss: 400.625, val task loss: 400.625
model_2: train loss: 380.275, train task loss: 380.275 - val loss: 426.045, val task loss: 426.045
model_3: train loss: 423.081, train task loss: 423.081 - val loss: 444.650, val task loss: 444.650
Training with disagreement penalty = 0.99
Computing divergence weights by clustering method...
Initialization complete
Iteration 0, inertia 69.22709226701409.
Iteration 1, inertia 34.61354613350704.
Converged at iteration 1: strict convergence.
Computed divergence weights by clustering method, weights are [0.5 0.5 0. ]

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3569.04it/s]

model_1: train loss: 412.424, train task loss: 368.130 - val loss: 421.455, val task loss: 384.556 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/0.99
model_2: train loss: 406.848, train task loss: 362.554 - val loss: 402.495, val task loss: 365.596 [*] Best so far
model_3: train loss: 475.842, train task loss: 386.360 - val loss: 463.093, val task loss: 395.301 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3816.07it/s]

model_1: train loss: 395.537, train task loss: 355.706 - val loss: 422.674, val task loss: 388.293
model_2: train loss: 406.727, train task loss: 366.896 - val loss: 398.162, val task loss: 363.781 [*] Best so far
model_3: train loss: 457.888, train task loss: 386.329 - val loss: 509.668, val task loss: 428.851

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3940.89it/s]

model_1: train loss: 387.570, train task loss: 346.018 - val loss: 428.786, val task loss: 390.676
model_2: train loss: 410.713, train task loss: 369.161 - val loss: 405.827, val task loss: 367.716
model_3: train loss: 464.977, train task loss: 393.218 - val loss: 495.770, val task loss: 417.789

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3653.73it/s]

model_1: train loss: 381.438, train task loss: 333.822 - val loss: 438.607, val task loss: 392.854
model_2: train loss: 423.659, train task loss: 376.043 - val loss: 422.346, val task loss: 376.593
model_3: train loss: 469.285, train task loss: 390.887 - val loss: 533.778, val task loss: 432.968

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3792.93it/s]

model_1: train loss: 369.381, train task loss: 321.202 - val loss: 438.904, val task loss: 395.863
model_2: train loss: 420.874, train task loss: 372.696 - val loss: 407.246, val task loss: 364.204
model_3: train loss: 485.304, train task loss: 398.357 - val loss: 518.554, val task loss: 419.877

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3736.44it/s]

model_1: train loss: 363.911, train task loss: 307.842 - val loss: 485.093, val task loss: 398.629
model_2: train loss: 437.667, train task loss: 381.598 - val loss: 542.154, val task loss: 455.690
model_3: train loss: 527.550, train task loss: 410.836 - val loss: 507.450, val task loss: 390.395 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3633.61it/s]

model_1: train loss: 345.155, train task loss: 295.233 - val loss: 447.414, val task loss: 402.162
model_2: train loss: 406.134, train task loss: 356.212 - val loss: 400.790, val task loss: 355.538 [*] Best so far
model_3: train loss: 483.690, train task loss: 394.591 - val loss: 492.763, val task loss: 412.896

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3552.68it/s]

model_1: train loss: 333.426, train task loss: 283.566 - val loss: 473.834, val task loss: 405.866
model_2: train loss: 412.359, train task loss: 362.498 - val loss: 460.020, val task loss: 392.052
model_3: train loss: 471.674, train task loss: 385.197 - val loss: 479.552, val task loss: 389.959 [*] Best so far

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3649.71it/s]

model_1: train loss: 332.088, train task loss: 271.721 - val loss: 484.351, val task loss: 408.356
model_2: train loss: 436.432, train task loss: 376.066 - val loss: 474.565, val task loss: 398.570
model_3: train loss: 504.398, train task loss: 396.133 - val loss: 530.062, val task loss: 412.273

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3680.87it/s]

model_1: train loss: 304.873, train task loss: 258.816 - val loss: 464.375, val task loss: 413.882
model_2: train loss: 380.389, train task loss: 334.332 - val loss: 398.084, val task loss: 347.591 [*] Best so far
model_3: train loss: 485.334, train task loss: 390.918 - val loss: 577.774, val task loss: 453.948
Training with disagreement penalty = 3

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3130.48it/s]

model_1: train loss: 844.704, train task loss: 498.115 - val loss: 615.593, val task loss: 442.442 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/3
model_2: train loss: 1057.171, train task loss: 710.581 - val loss: 665.054, val task loss: 491.902 [*] Best so far
model_3: train loss: 1409.752, train task loss: 603.132 - val loss: 624.640, val task loss: 434.203 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3562.85it/s]

model_1: train loss: 544.218, train task loss: 481.359 - val loss: 478.611, val task loss: 430.647 [*] Best so far
model_2: train loss: 573.982, train task loss: 511.123 - val loss: 470.077, val task loss: 422.114 [*] Best so far
model_3: train loss: 547.642, train task loss: 479.767 - val loss: 474.975, val task loss: 427.344 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3878.86it/s]

model_1: train loss: 479.690, train task loss: 460.299 - val loss: 428.970, val task loss: 415.391 [*] Best so far
model_2: train loss: 466.721, train task loss: 447.329 - val loss: 413.999, val task loss: 400.420 [*] Best so far
model_3: train loss: 496.833, train task loss: 453.775 - val loss: 450.140, val task loss: 424.871 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3759.39it/s]

model_1: train loss: 459.405, train task loss: 433.817 - val loss: 425.798, val task loss: 401.436 [*] Best so far
model_2: train loss: 441.137, train task loss: 415.549 - val loss: 413.594, val task loss: 389.232 [*] Best so far
model_3: train loss: 479.101, train task loss: 439.127 - val loss: 446.173, val task loss: 407.709 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3818.90it/s]

model_1: train loss: 440.799, train task loss: 409.275 - val loss: 425.924, val task loss: 394.947 [*] Best so far
model_2: train loss: 434.471, train task loss: 402.947 - val loss: 413.175, val task loss: 382.198 [*] Best so far
model_3: train loss: 473.541, train task loss: 424.358 - val loss: 450.202, val task loss: 403.681 [*] Best so far

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3966.60it/s]

model_1: train loss: 431.896, train task loss: 392.226 - val loss: 439.477, val task loss: 392.539 [*] Best so far
model_2: train loss: 433.023, train task loss: 393.352 - val loss: 427.771, val task loss: 380.833 [*] Best so far
model_3: train loss: 479.347, train task loss: 418.927 - val loss: 467.437, val task loss: 402.881 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3118.66it/s]

model_1: train loss: 431.779, train task loss: 380.177 - val loss: 439.734, val task loss: 394.220
model_2: train loss: 436.215, train task loss: 384.613 - val loss: 422.695, val task loss: 377.181 [*] Best so far
model_3: train loss: 488.899, train task loss: 414.028 - val loss: 501.417, val task loss: 413.315

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3844.52it/s]

model_1: train loss: 418.984, train task loss: 371.580 - val loss: 451.400, val task loss: 396.170
model_2: train loss: 433.857, train task loss: 386.453 - val loss: 433.489, val task loss: 378.259
model_3: train loss: 492.454, train task loss: 410.986 - val loss: 507.439, val task loss: 410.134

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 4088.92it/s]

model_1: train loss: 408.472, train task loss: 361.960 - val loss: 450.245, val task loss: 398.191
model_2: train loss: 419.476, train task loss: 372.964 - val loss: 422.478, val task loss: 370.424 [*] Best so far
model_3: train loss: 498.198, train task loss: 412.750 - val loss: 467.060, val task loss: 397.485 [*] Best so far

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 3898.46it/s]

model_1: train loss: 406.123, train task loss: 353.297 - val loss: 506.177, val task loss: 399.497
model_2: train loss: 422.040, train task loss: 369.214 - val loss: 515.475, val task loss: 408.795
model_3: train loss: 496.651, train task loss: 404.262 - val loss: 525.227, val task loss: 398.242
Finished training student cohort!
Selecting the optimal disgreement penalty via cross-validation...
Best rho: 0.99 with average task loss: 366.0737
Done!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [1, 0] with losses: [tensor(347.5914, grad_fn=<MseLossBackward0>), tensor(384.5560, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 323.3274230957031
Method: (weighted_average), Test_MSE: 322.3891906738281
Method: (greedy_ensemble), Test_MSE: 318.6562805175781
Method: (best_single), Test_MSE: 329.6678771972656
Method: (cohort), Test_MSE: [354.6806640625, 329.6678771972656, 361.2091064453125]
Method: (simple_average), Test_MSE: 327.01922607421875
Method: (weighted_average), Test_MSE: 326.81610107421875
Method: (greedy_ensemble), Test_MSE: 330.2935791015625
Method: (best_single), Test_MSE: 351.4432067871094
Method: (cohort), Test_MSE: [356.2692565917969, 351.4432067871094, 367.1004943847656]
Finished running meta fusion!
Start training student cohort...

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2065.00it/s, loss=477.1026, batch_time=0.031s]

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2084.55it/s, loss=411.2862, batch_time=0.031s]

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 1826.61it/s, loss=345.5358, batch_time=0.035s]

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2133.75it/s, loss=298.8326, batch_time=0.030s]

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2159.02it/s, loss=268.6647, batch_time=0.030s]

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2211.90it/s, loss=248.1087, batch_time=0.029s]

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2145.71it/s, loss=232.5408, batch_time=0.030s]

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2237.12it/s, loss=222.5644, batch_time=0.029s]

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 1955.82it/s, loss=210.4406, batch_time=0.033s]

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2174.28it/s, loss=197.0511, batch_time=0.029s]

Finished training student cohort!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [0, 1] with losses: [tensor(524.7124, grad_fn=<MseLossBackward0>), tensor(31344.7188, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 271.2450866699219
Method: (weighted_average), Test_MSE: 271.1322326660156
Method: (greedy_ensemble), Test_MSE: 318.57293701171875
Method: (best_single), Test_MSE: 476.7852783203125
Method: (cohort), Test_MSE: [476.7852783203125, 536.994140625, 491.1130676269531]
Finished running joint fusion!
Start training student cohort...

Epoch: 1/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1436.15it/s, avg_loss=471.2334, batch_time=0.045s]

Epoch: 2/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1349.50it/s, avg_loss=404.4846, batch_time=0.047s]

Epoch: 3/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1313.63it/s, avg_loss=353.4645, batch_time=0.049s]

Epoch: 4/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1377.28it/s, avg_loss=322.1421, batch_time=0.046s]

Epoch: 5/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1411.85it/s, avg_loss=304.1038, batch_time=0.045s]

Epoch: 6/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:01<00:00, 1265.27it/s, avg_loss=289.3931, batch_time=0.051s]

Epoch: 7/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1457.54it/s, avg_loss=276.7514, batch_time=0.044s]

Epoch: 8/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1430.47it/s, avg_loss=262.7507, batch_time=0.045s]

Epoch: 9/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1447.39it/s, avg_loss=250.4232, batch_time=0.044s]

Epoch: 10/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1342.49it/s, avg_loss=239.1647, batch_time=0.048s]
Repetitions: 100%|██████████| 1/1 [00:30<00:00, 30.53s/it]

Finished training student cohort!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [1, 0] with losses: [tensor(357.0607, grad_fn=<MseLossBackward0>), tensor(463.9885, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 290.61163330078125
Method: (weighted_average), Test_MSE: 285.4935607910156
Method: (greedy_ensemble), Test_MSE: 307.0782775878906
Method: (best_single), Test_MSE: 341.9085693359375
Method: (cohort), Test_MSE: [428.3910217285156, 341.1065368652344, 361.194091796875]
Finished running shapley fusion!

,Method,Test_metric,best_rho,cohort_pairs,ensemble_idxs,cluster_idxs,random_state,dim_modalities,n,n_train,n_val,n_test,extractor,weight_type
0,modality_1,359.345306,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
1,modality_2,332.801178,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
2,modality_3,360.946198,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
3,early_fusion,315.762024,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
4,late_fusion,312.86676,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
5,metafusion_simple_average,323.327423,0.99,"[200, 300, 100]",None,"[0, 1]",1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
6,metafusion_weighted_average,322.389191,0.99,"[200, 300, 100]",None,"[0, 1]",1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
7,metafusion_greedy_ensemble,318.656281,0.99,"[200, 300, 100]","[1, 0]","[0, 1]",1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
8,metafusion_best_single,329.667877,0.99,"[200, 300, 100]",None,"[0, 1]",1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
9,metafusion_cohort,"[354.6806640625, 329.6678771972656, 361.209106...",0.99,"[200, 300, 100]",None,"[0, 1]",1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
10,indep_simple_average,327.019226,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
11,indep_weighted_average,326.816101,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
12,indep_greedy_ensemble,330.293579,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
13,indep_best_single,351.443207,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
14,indep_cohort,"[356.2692565917969, 351.4432067871094, 367.100...",NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
15,jointlearning_simple_average,271.245087,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
16,jointlearning_weighted_average,271.132233,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
17,jointlearning_greedy_ensemble,318.572937,NaN,None,"[0, 1]",None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
18,jointlearning_best_single,476.785278,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
19,jointlearning_cohort,"[476.7852783203125, 536.994140625, 491.1130676...",NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
20,shapley_simple_average,290.611633,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
21,shapley_weighted_average,285.493561,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
22,shapley_greedy_ensemble,307.078278,NaN,None,"[1, 0]",None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
23,shapley_best_single,341.908569,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
24,shapley_cohort,"[428.3910217285156, 341.1065368652344, 361.194...",NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering

:

:

:

In [6]:
EXPERIMENT_VARIANT = "imputation"

# Build a filename that encodes the key experiment parameters
outfile_name = (
    f"{EXPERIMENT_VARIANT}_"
    f"dim_modalities{dim_modalities}_"
    f"noise{noise_ratios}_"
    f"trans{trans_label}_"
    f"fractions{fractions}_"
    f"seed{seed}"
)
# sanitize characters that are annoying in filenames
outfile_name = (
    outfile_name.replace(" ", "")
    .replace("[", "(")
    .replace("]", ")")
    .replace(",", "-")
)

outfile = outdir + outfile_name + ".txt"
print("Output file: {:s}".format(outfile), end="\n")
sys.stdout.flush()


#####################
#    Save Results   #
#####################
results.to_csv(outfile, index=False)
print("\nResults written to {:s}\n".format(outfile))
sys.stdout.flush()

# After the job is done, remove the model directory to free up space
if os.path.exists(ckpt_dir):
    print(f"Deleting the model checkpoint directory: {ckpt_dir}")
    shutil.rmtree(ckpt_dir)
    print(f"Model checkpoint directory {ckpt_dir} has been deleted.")

Output file: ./results/regression_linear_early/imputation_dim_modalities(200-300-100)_noise(0.6-0.1-0.1)_transm1linear_m2quadratic_m3quadratic_sharedlinear_fractions(1-0.8-0.6)_seed1234.txt

Results written to ./results/regression_linear_early/imputation_dim_modalities(200-300-100)_noise(0.6-0.1-0.1)_transm1linear_m2quadratic_m3quadratic_sharedlinear_fractions(1-0.8-0.6)_seed1234.txt

In [ ]:
### Filtering the data

In [3]:
#####################
# Define Experiment #
#####################
def run_single_experiment_filter(config, extractor_config, n, random_state, mod_hiddens,
                          run_oracle=False, run_coop=True, run_all_at_once=False):


    config['random_state'] = random_state
    extractor_config['random_state'] = random_state
    res_list = []
    best_rho = {}
    cohort_pairs = {}
    ens_idxs = {}
    cluster_idxs = {}


    #----------------#
    # Split dataset  #
    #----------------#
    train_loader, val_loader, test_loader, oracle_train_loader, oracle_val_loader, oracle_test_loader =\
    data_preparer.get_data_loaders(n, trans_type=trans_type, mod_prop=mod_prop, 
                                    interactive_prop = interactive_prop,
                                    dim_modalities=dim_modalities, dim_latent=dim_latent,
                                    noise_ratios=noise_ratios, random_state=random_state)
    # Get data info
    train_miss, val_miss, test_miss = data_preparer.apply_missing_modalities(
        train_loader, val_loader, test_loader, modality_fractions=fractions, random_state=0,
        missing_value=missing_value
    )                     ### based on presence fraction of each modality, randomly mask some values to missing_value.          
    train_loader, val_loader, test_loader = data_preparer.filter_fully_observed(
        train_miss, val_miss, test_miss, missing_value=missing_value
    )  #### Only keep the datapoints that have all modalities present. 
    # After applying missingness / filtering, sizes should come from the loaders
    n_train = len(train_loader.dataset)
    n_val = len(val_loader.dataset)
    n_test = len(test_loader.dataset)
    n = n_train + n_val + n_test

    print(f"Finished splitting {data_name} dataset. Data information are summarized below:\n"
            f"Modality dimensions: {dim_modalities}\n"
            f"Data size: {n}\n"
            f"Train size: {n_train}\n"
            f"Val size: {n_val}\n"
            f"Test size: {n_test}")
    sys.stdout.flush() 

    #------------------#
    # Benchmark models #
    #------------------#
    bm_extractor = Extractors([[d,0] for d in dim_modalities], dim_modalities, train_loader, val_loader)
    _ = bm_extractor.get_dummy_extractors()
    bm_cohort = Cohorts(extractors=bm_extractor, combined_hidden_layers=combined_hiddens, output_dim=output_dim)

    if run_oracle:
        oracle_dims = [dim_latent[0], dim_latent[1]+dim_latent[2]]
        oracle_extractor = Extractors([[d,0] for d in oracle_dims], oracle_dims, oracle_train_loader, oracle_val_loader)
        _ = oracle_extractor.get_dummy_extractors()
        oracle_cohort = Cohorts(extractors=oracle_extractor, combined_hidden_layers=combined_hiddens, output_dim=output_dim)

    #----------------------------#
    # Proposed model: Meta Fuse  #
    #----------------------------#
    meta_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)

    #------------------------------#
    #  Train and test benchmarks   #
    #------------------------------#
    bm_models = bm_cohort.get_cohort_models()
    _, bm_dims = bm_cohort.get_cohort_info()
    bm = Benchmarks(config, bm_models, bm_dims, [train_loader, val_loader])
    bm.train()
    res = bm.test(test_loader)
    res_list.append(res)
    print(f"Finished running basic benchmarks!")

    #------------------------------#
    #  Train and test Meta Fuse    #
    #------------------------------#
    cohort_models = meta_cohort.get_cohort_models()
    _, dim_pairs = meta_cohort.get_cohort_info()
    ###### Only change the two following.
    metafuse = Trainer_new(config, cohort_models, [train_loader, val_loader]) # New trainer function. 
    metafuse.train() 
    res = metafuse.test(test_loader) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"metafusion_{k}": v for k, v in res.items()}
    res_list.append(res)
    metafuse.train_ablation() # This is just late fusion with student cohort.
    res = metafuse.test_ablation(test_loader) # I don't need this, no need to have different rhos.
    res = {f"indep_{k}": v for k, v in res.items()}
    res_list.append(res)

    best_rho['metafusion'] = metafuse.best_rho
    cohort_pairs['metafusion'] = dim_pairs
    cohort_pairs['indep'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['metafusion_greedy_ensemble'] = metafuse.ens_idxs  

    if config['divergence_weight_type'] == "clustering":
        cluster_idxs['metafusion'] = metafuse.cluster_idxs

    print(f"Finished running meta fusion!")

    #----------------------------#
    # Proposed model: Joint train#
    #----------------------------#
    # joint_extractor = Extractors(mod_outs, dim_modalities, train_loader, val_loader)
    # if (extractor_type == 'encoder') or (extractor_type == 'separate'):
    #     _ = joint_extractor.get_encoder_extractors(mod_hiddens, separate=separate, config=extractor_config)
    # elif extractor_type == 'PCA':
    #     _ = joint_extractor.get_PCA_extractors()

    n_train = len(train_miss.dataset)
    n_val = len(val_miss.dataset)
    n_test = len(test_miss.dataset)
    n = n_train + n_val + n_test

    print(f"Finished splitting {data_name} dataset. Data information are summarized below:\n"
            f"Modality dimensions: {dim_modalities}\n"
            f"Data size: {n}\n"
            f"Train size: {n_train}\n"
            f"Val size: {n_val}\n"
            f"Test size: {n_test}")
    sys.stdout.flush() 

    joint_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)

    # ------------------------------#
    #  Train and test Joint train  #
    # ------------------------------#
    cohort_models = joint_cohort.get_cohort_models()
    _, dim_pairs = joint_cohort.get_cohort_info()
    ###### Only change the two following.
    jointmodel = Trainer_Joint_new(config, cohort_models, [train_miss, val_miss]) # New trainer function. 
    jointmodel.train('marginal', missing_value=missing_value) 
    res = jointmodel.test(test_miss, missing_value=missing_value) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"jointlearning_{k}": v for k, v in res.items()}
    res_list.append(res)
    cohort_pairs['cohort'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['jointlearning_greedy_ensemble'] = jointmodel.ens_idxs  


    print(f"Finished running joint fusion!")

    #----------------------------#
    # Proposed model: Shapley train#
    #----------------------------#
    joint_cohort = Cohorts_new(dim_modalities = dim_modalities, num_modalities= num_modalities, mod_hiddens  = mod_hiddens, output_dim=output_dim)

    #------------------------------#
    #  Train and test shapley train  #
    #------------------------------#
    cohort_models = joint_cohort.get_cohort_models()
    _, dim_pairs = joint_cohort.get_cohort_info()
    ###### Only change the two following.
    jointmodel = Trainer_Joint_new(config, cohort_models, [train_miss, val_miss]) # New trainer function. 
    jointmodel.train('shapley', missing_value=missing_value) 
    res = jointmodel.test(test_miss, missing_value=missing_value) # No need to change test: simple_averaging in test_regresion() also # performance of each student on the test data, cohort_accuracy: automaticall printed and stored. 
    res = {f"shapley_{k}": v for k, v in res.items()}
    res_list.append(res)
    cohort_pairs['cohort'] = dim_pairs

    if "greedy_ensemble" in config["ensemble_methods"]:
        ens_idxs['shapley_greedy_ensemble'] = jointmodel.ens_idxs  


    print(f"Finished running shapley fusion!")        

    results = []
    for i, res in enumerate(res_list):
        for method, val in res.items():
            results.append({'Method': method, 'Test_metric': val, 
                            'best_rho':best_rho.get(method.split('_')[0]), 'cohort_pairs':cohort_pairs.get(method.split('_')[0]),
                            'ensemble_idxs': ens_idxs.get(method), 'cluster_idxs': cluster_idxs.get(method.split('_')[0])})

    results = pd.DataFrame(results)
    results['random_state']=random_state
    results["dim_modalities"] = [dim_modalities] * len(results)
    results['n'] = n
    results['n_train'] = n_train
    results['n_val'] = n_val
    results['n_test'] = n_test 

    return results

In [4]:
#####################
#  Run Experiments  #
#####################
results = []

for i in tqdm(range(1, repetition+1), desc="Repetitions", leave=True, position=0):
    print(f'Running with repetition {i}...')
    random_state = repetition * (seed-1) + i
    # print(random_state)
    set_random_seed(random_state)

    # Run experiment
    tmp = run_single_experiment_filter(config, extractor_config, n, random_state, mod_hiddens,
                                run_oracle=False, run_coop=True, run_all_at_once=False)
    
    results.append(tmp)


results = pd.concat(results, ignore_index=True)

add_header(results)

Repetitions:   0%|          | 0/1 [00:00<?, ?it/s]

Running with repetition 1...
Finished splitting regression dataset. Data information are summarized below:
Modality dimensions: [200, 300, 100]
Data size: 971
Train size: 619
Val size: 151
Test size: 201

/Users/parnian/Desktop/Github/Multimodal-ML/notebooks/../meta_fusion/utils.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.data = torch.tensor(data, dtype=torch.float32)

Start training benchmark models...
Training with disagreement penalty = 0

Epoch: 1/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 2304.60it/s]

model_1: train loss: 491.250, train task loss: 491.250 - val loss: 410.563, val task loss: 410.563 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/0
model_2: train loss: 490.608, train task loss: 490.608 - val loss: 406.924, val task loss: 406.924 [*] Best so far
model_3: train loss: 492.066, train task loss: 492.066 - val loss: 409.229, val task loss: 409.229 [*] Best so far
model_4: train loss: 489.028, train task loss: 489.028 - val loss: 404.303, val task loss: 404.303 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3286.24it/s]

model_1: train loss: 483.801, train task loss: 483.801 - val loss: 404.079, val task loss: 404.079 [*] Best so far
model_2: train loss: 476.536, train task loss: 476.536 - val loss: 391.370, val task loss: 391.370 [*] Best so far
model_3: train loss: 477.674, train task loss: 477.674 - val loss: 395.648, val task loss: 395.648 [*] Best so far
model_4: train loss: 463.079, train task loss: 463.079 - val loss: 379.829, val task loss: 379.829 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3334.05it/s]

model_1: train loss: 472.070, train task loss: 472.070 - val loss: 393.652, val task loss: 393.652 [*] Best so far
model_2: train loss: 450.863, train task loss: 450.863 - val loss: 363.129, val task loss: 363.129 [*] Best so far
model_3: train loss: 453.211, train task loss: 453.211 - val loss: 373.187, val task loss: 373.187 [*] Best so far
model_4: train loss: 409.269, train task loss: 409.269 - val loss: 334.888, val task loss: 334.888 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3272.79it/s]

model_1: train loss: 450.039, train task loss: 450.039 - val loss: 379.881, val task loss: 379.881 [*] Best so far
model_2: train loss: 407.078, train task loss: 407.078 - val loss: 331.316, val task loss: 331.316 [*] Best so far
model_3: train loss: 410.668, train task loss: 410.668 - val loss: 348.683, val task loss: 348.683 [*] Best so far
model_4: train loss: 323.115, train task loss: 323.115 - val loss: 289.835, val task loss: 289.835 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3226.30it/s]

model_1: train loss: 421.538, train task loss: 421.538 - val loss: 366.312, val task loss: 366.312 [*] Best so far
model_2: train loss: 369.586, train task loss: 369.586 - val loss: 328.724, val task loss: 328.724 [*] Best so far
model_3: train loss: 370.845, train task loss: 370.845 - val loss: 340.754, val task loss: 340.754 [*] Best so far
model_4: train loss: 261.679, train task loss: 261.679 - val loss: 281.906, val task loss: 281.906 [*] Best so far

Epoch: 6/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3115.86it/s]

model_1: train loss: 387.210, train task loss: 387.210 - val loss: 361.360, val task loss: 361.360 [*] Best so far
model_2: train loss: 345.775, train task loss: 345.775 - val loss: 330.481, val task loss: 330.481
model_3: train loss: 349.934, train task loss: 349.934 - val loss: 340.612, val task loss: 340.612 [*] Best so far
model_4: train loss: 218.876, train task loss: 218.876 - val loss: 271.883, val task loss: 271.883 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3252.93it/s]

model_1: train loss: 357.514, train task loss: 357.514 - val loss: 364.722, val task loss: 364.722
model_2: train loss: 325.927, train task loss: 325.927 - val loss: 314.978, val task loss: 314.978 [*] Best so far
model_3: train loss: 335.756, train task loss: 335.756 - val loss: 334.389, val task loss: 334.389 [*] Best so far
model_4: train loss: 180.067, train task loss: 180.067 - val loss: 268.218, val task loss: 268.218 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3363.35it/s]

model_1: train loss: 338.595, train task loss: 338.595 - val loss: 373.296, val task loss: 373.296
model_2: train loss: 307.434, train task loss: 307.434 - val loss: 314.827, val task loss: 314.827 [*] Best so far
model_3: train loss: 321.824, train task loss: 321.824 - val loss: 331.351, val task loss: 331.351 [*] Best so far
model_4: train loss: 149.352, train task loss: 149.352 - val loss: 274.499, val task loss: 274.499

Epoch: 9/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3265.44it/s]

model_1: train loss: 319.116, train task loss: 319.116 - val loss: 375.183, val task loss: 375.183
model_2: train loss: 287.331, train task loss: 287.331 - val loss: 309.496, val task loss: 309.496 [*] Best so far
model_3: train loss: 311.509, train task loss: 311.509 - val loss: 330.732, val task loss: 330.732 [*] Best so far
model_4: train loss: 121.877, train task loss: 121.877 - val loss: 276.418, val task loss: 276.418

Epoch: 10/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3098.55it/s]

model_1: train loss: 298.920, train task loss: 298.920 - val loss: 380.709, val task loss: 380.709
model_2: train loss: 270.213, train task loss: 270.213 - val loss: 314.524, val task loss: 314.524
model_3: train loss: 303.809, train task loss: 303.809 - val loss: 331.458, val task loss: 331.458
model_4: train loss: 98.861, train task loss: 98.861 - val loss: 275.922, val task loss: 275.922
Finished training benchmark models!
Method: (modality_1), Test_MSE: 393.4906005859375
Method: (modality_2), Test_MSE: 369.7848205566406
Method: (modality_3), Test_MSE: 377.91912841796875
Method: (early_fusion), Test_MSE: 282.359130859375
Method: (late_fusion), Test_MSE: 331.149169921875
Finished running basic benchmarks!
Start training student cohort...
Training with disagreement penalty = 0

Epoch: 1/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4051.58it/s]

model_1: train loss: 493.539, train task loss: 493.539 - val loss: 412.766, val task loss: 412.766 [*] Best so far
model_2: train loss: 487.974, train task loss: 487.974 - val loss: 398.776, val task loss: 398.776 [*] Best so far
model_3: train loss: 485.589, train task loss: 485.589 - val loss: 402.976, val task loss: 402.976 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4952.92it/s]

model_1: train loss: 481.335, train task loss: 481.335 - val loss: 406.251, val task loss: 406.251 [*] Best so far
model_2: train loss: 461.572, train task loss: 461.572 - val loss: 378.667, val task loss: 378.667 [*] Best so far
model_3: train loss: 463.161, train task loss: 463.161 - val loss: 389.465, val task loss: 389.465 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4893.83it/s]

model_1: train loss: 470.506, train task loss: 470.506 - val loss: 399.463, val task loss: 399.463 [*] Best so far
model_2: train loss: 436.764, train task loss: 436.764 - val loss: 357.127, val task loss: 357.127 [*] Best so far
model_3: train loss: 441.561, train task loss: 441.561 - val loss: 375.653, val task loss: 375.653 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4951.73it/s]

model_1: train loss: 456.807, train task loss: 456.807 - val loss: 393.027, val task loss: 393.027 [*] Best so far
model_2: train loss: 406.242, train task loss: 406.242 - val loss: 339.732, val task loss: 339.732 [*] Best so far
model_3: train loss: 415.988, train task loss: 415.988 - val loss: 362.715, val task loss: 362.715 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 5094.66it/s]

model_1: train loss: 441.804, train task loss: 441.804 - val loss: 385.774, val task loss: 385.774 [*] Best so far
model_2: train loss: 379.476, train task loss: 379.476 - val loss: 326.714, val task loss: 326.714 [*] Best so far
model_3: train loss: 389.280, train task loss: 389.280 - val loss: 352.633, val task loss: 352.633 [*] Best so far

Epoch: 6/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4948.04it/s]

model_1: train loss: 424.881, train task loss: 424.881 - val loss: 378.883, val task loss: 378.883 [*] Best so far
model_2: train loss: 358.368, train task loss: 358.368 - val loss: 320.155, val task loss: 320.155 [*] Best so far
model_3: train loss: 366.189, train task loss: 366.189 - val loss: 346.447, val task loss: 346.447 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4470.53it/s]

model_1: train loss: 405.866, train task loss: 405.866 - val loss: 372.627, val task loss: 372.627 [*] Best so far
model_2: train loss: 340.518, train task loss: 340.518 - val loss: 319.466, val task loss: 319.466 [*] Best so far
model_3: train loss: 346.944, train task loss: 346.944 - val loss: 343.948, val task loss: 343.948 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4567.89it/s]

model_1: train loss: 386.604, train task loss: 386.604 - val loss: 367.518, val task loss: 367.518 [*] Best so far
model_2: train loss: 327.457, train task loss: 327.457 - val loss: 319.139, val task loss: 319.139 [*] Best so far
model_3: train loss: 335.154, train task loss: 335.154 - val loss: 343.800, val task loss: 343.800 [*] Best so far

Epoch: 9/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 5075.28it/s]

model_1: train loss: 367.179, train task loss: 367.179 - val loss: 365.019, val task loss: 365.019 [*] Best so far
model_2: train loss: 315.815, train task loss: 315.815 - val loss: 316.285, val task loss: 316.285 [*] Best so far
model_3: train loss: 326.827, train task loss: 326.827 - val loss: 344.016, val task loss: 344.016

Epoch: 10/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 4189.99it/s]

model_1: train loss: 348.261, train task loss: 348.261 - val loss: 364.980, val task loss: 364.980 [*] Best so far
model_2: train loss: 304.562, train task loss: 304.562 - val loss: 317.993, val task loss: 317.993
model_3: train loss: 319.488, train task loss: 319.488 - val loss: 342.281, val task loss: 342.281 [*] Best so far
Training with disagreement penalty = 0.99
Computing divergence weights by clustering method...
Initialization complete
Iteration 0, inertia 515.2836267286912.
Iteration 1, inertia 257.6418133643456.
Converged at iteration 1: strict convergence.
Computed divergence weights by clustering method, weights are [0. 1. 0.]

Epoch: 1/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 2405.70it/s]

model_1: train loss: 440.022, train task loss: 331.600 - val loss: 516.951, val task loss: 365.741 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/0.99
model_2: train loss: 305.019, train task loss: 305.019 - val loss: 317.697, val task loss: 317.697 [*] Best so far
model_3: train loss: 491.621, train task loss: 315.420 - val loss: 524.938, val task loss: 332.615 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3337.81it/s]

model_1: train loss: 422.127, train task loss: 315.843 - val loss: 522.885, val task loss: 366.278
model_2: train loss: 295.087, train task loss: 295.087 - val loss: 316.073, val task loss: 316.073 [*] Best so far
model_3: train loss: 468.417, train task loss: 319.677 - val loss: 495.793, val task loss: 326.662 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3147.90it/s]

model_1: train loss: 404.920, train task loss: 302.884 - val loss: 528.180, val task loss: 366.975
model_2: train loss: 284.832, train task loss: 284.832 - val loss: 314.295, val task loss: 314.295 [*] Best so far
model_3: train loss: 462.392, train task loss: 327.810 - val loss: 484.560, val task loss: 323.194 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3784.13it/s]

model_1: train loss: 383.949, train task loss: 288.879 - val loss: 531.975, val task loss: 369.139
model_2: train loss: 275.804, train task loss: 275.804 - val loss: 311.494, val task loss: 311.494 [*] Best so far
model_3: train loss: 458.978, train task loss: 328.796 - val loss: 482.588, val task loss: 320.671 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3622.35it/s]

model_1: train loss: 364.750, train task loss: 275.637 - val loss: 537.734, val task loss: 370.728
model_2: train loss: 265.390, train task loss: 265.390 - val loss: 309.960, val task loss: 309.960 [*] Best so far
model_3: train loss: 454.985, train task loss: 325.629 - val loss: 484.626, val task loss: 318.359 [*] Best so far

Epoch: 6/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3553.33it/s]

model_1: train loss: 348.679, train task loss: 260.884 - val loss: 553.965, val task loss: 373.448
model_2: train loss: 255.749, train task loss: 255.749 - val loss: 310.338, val task loss: 310.338
model_3: train loss: 456.855, train task loss: 321.090 - val loss: 495.362, val task loss: 317.196 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3825.12it/s]

model_1: train loss: 334.411, train task loss: 246.897 - val loss: 565.451, val task loss: 375.889
model_2: train loss: 244.975, train task loss: 244.975 - val loss: 305.547, val task loss: 305.547 [*] Best so far
model_3: train loss: 459.565, train task loss: 315.469 - val loss: 507.466, val task loss: 315.947 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3814.24it/s]

model_1: train loss: 316.688, train task loss: 232.593 - val loss: 570.524, val task loss: 378.439
model_2: train loss: 234.161, train task loss: 234.161 - val loss: 300.856, val task loss: 300.856 [*] Best so far
model_3: train loss: 458.687, train task loss: 312.255 - val loss: 505.005, val task loss: 314.819 [*] Best so far

Epoch: 9/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3523.03it/s]

model_1: train loss: 299.735, train task loss: 219.514 - val loss: 584.837, val task loss: 381.891
model_2: train loss: 224.171, train task loss: 224.171 - val loss: 300.032, val task loss: 300.032 [*] Best so far
model_3: train loss: 457.030, train task loss: 310.780 - val loss: 512.846, val task loss: 314.326 [*] Best so far

Epoch: 10/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3250.06it/s]

model_1: train loss: 281.140, train task loss: 206.067 - val loss: 597.300, val task loss: 385.843
model_2: train loss: 212.659, train task loss: 212.659 - val loss: 298.938, val task loss: 298.938 [*] Best so far
model_3: train loss: 455.244, train task loss: 310.544 - val loss: 517.299, val task loss: 314.055 [*] Best so far
Training with disagreement penalty = 3

Epoch: 1/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3301.76it/s]

model_1: train loss: 494.501, train task loss: 493.724 - val loss: 415.451, val task loss: 412.921 [*] Best so far
Created directory: ./checkpoints/regression_linear_early/seed1234/3
model_2: train loss: 487.843, train task loss: 487.843 - val loss: 398.914, val task loss: 398.914 [*] Best so far
model_3: train loss: 486.732, train task loss: 485.673 - val loss: 405.624, val task loss: 402.585 [*] Best so far

Epoch: 2/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3679.77it/s]

model_1: train loss: 486.195, train task loss: 481.338 - val loss: 416.970, val task loss: 405.882 [*] Best so far
model_2: train loss: 461.086, train task loss: 461.086 - val loss: 378.113, val task loss: 378.113 [*] Best so far
model_3: train loss: 470.455, train task loss: 463.973 - val loss: 402.761, val task loss: 389.663 [*] Best so far

Epoch: 3/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3689.35it/s]

model_1: train loss: 484.908, train task loss: 469.675 - val loss: 430.152, val task loss: 399.018 [*] Best so far
model_2: train loss: 435.524, train task loss: 435.524 - val loss: 356.731, val task loss: 356.731 [*] Best so far
model_3: train loss: 463.869, train task loss: 443.922 - val loss: 412.594, val task loss: 376.824 [*] Best so far

Epoch: 4/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3779.85it/s]

model_1: train loss: 496.137, train task loss: 457.050 - val loss: 461.166, val task loss: 391.526 [*] Best so far
model_2: train loss: 407.060, train task loss: 407.060 - val loss: 338.653, val task loss: 338.653 [*] Best so far
model_3: train loss: 471.781, train task loss: 423.637 - val loss: 439.585, val task loss: 365.081 [*] Best so far

Epoch: 5/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3403.02it/s]

model_1: train loss: 519.711, train task loss: 442.180 - val loss: 517.273, val task loss: 383.683 [*] Best so far
model_2: train loss: 379.849, train task loss: 379.849 - val loss: 323.749, val task loss: 323.749 [*] Best so far
model_3: train loss: 497.222, train task loss: 406.360 - val loss: 493.119, val task loss: 357.028 [*] Best so far

Epoch: 6/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3266.53it/s]

model_1: train loss: 557.919, train task loss: 426.447 - val loss: 587.541, val task loss: 376.560 [*] Best so far
model_2: train loss: 358.196, train task loss: 358.196 - val loss: 316.595, val task loss: 316.595 [*] Best so far
model_3: train loss: 545.919, train task loss: 394.046 - val loss: 559.643, val task loss: 349.199 [*] Best so far

Epoch: 7/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3259.32it/s]

model_1: train loss: 591.476, train task loss: 408.272 - val loss: 644.356, val task loss: 370.480 [*] Best so far
model_2: train loss: 339.981, train task loss: 339.981 - val loss: 314.672, val task loss: 314.672 [*] Best so far
model_3: train loss: 598.556, train task loss: 383.749 - val loss: 617.518, val task loss: 344.162 [*] Best so far

Epoch: 8/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 2720.40it/s]

model_1: train loss: 603.018, train task loss: 392.419 - val loss: 685.458, val task loss: 365.975 [*] Best so far
model_2: train loss: 326.858, train task loss: 326.858 - val loss: 315.712, val task loss: 315.712
model_3: train loss: 633.554, train task loss: 379.379 - val loss: 652.168, val task loss: 341.344 [*] Best so far

Epoch: 9/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3674.83it/s]

model_1: train loss: 604.607, train task loss: 377.689 - val loss: 720.821, val task loss: 363.857 [*] Best so far
model_2: train loss: 315.366, train task loss: 315.366 - val loss: 315.330, val task loss: 315.330
model_3: train loss: 663.516, train task loss: 375.035 - val loss: 685.196, val task loss: 336.727 [*] Best so far

Epoch: 10/10 - LR: 0.001000

100%|██████████| 619/619 [00:00<00:00, 3555.12it/s]

model_1: train loss: 591.887, train task loss: 363.281 - val loss: 728.635, val task loss: 362.288 [*] Best so far
model_2: train loss: 303.893, train task loss: 303.893 - val loss: 312.957, val task loss: 312.957 [*] Best so far
model_3: train loss: 676.230, train task loss: 369.248 - val loss: 691.963, val task loss: 334.371 [*] Best so far
Finished training student cohort!
Selecting the optimal disgreement penalty via cross-validation...
Best rho: 0.99 with average task loss: 298.9380
Done!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [1, 2] with losses: [tensor(298.9380, grad_fn=<MseLossBackward0>), tensor(314.0545, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 326.0542297363281
Method: (weighted_average), Test_MSE: 324.0520324707031
Method: (greedy_ensemble), Test_MSE: 318.82843017578125
Method: (best_single), Test_MSE: 358.4331359863281
Method: (cohort), Test_MSE: [390.05145263671875, 358.4331359863281, 365.56884765625]
Method: (simple_average), Test_MSE: 334.2950744628906
Method: (weighted_average), Test_MSE: 333.400146484375
Method: (greedy_ensemble), Test_MSE: 328.5226135253906
Method: (best_single), Test_MSE: 378.6466064453125
Method: (cohort), Test_MSE: [393.0150451660156, 378.6466064453125, 373.9244689941406]
Finished running meta fusion!
Finished splitting regression dataset. Data information are summarized below:
Modality dimensions: [200, 300, 100]
Data size: 2000
Train size: 1280
Val size: 320
Test size: 400
Start training student cohort...

Epoch: 1/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2156.13it/s, loss=474.0191, batch_time=0.030s]

Epoch: 2/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2075.89it/s, loss=404.4933, batch_time=0.031s]

Epoch: 3/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 1961.70it/s, loss=343.7585, batch_time=0.033s]

Epoch: 4/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2138.89it/s, loss=295.6221, batch_time=0.030s]

Epoch: 5/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2003.44it/s, loss=262.5779, batch_time=0.032s]

Epoch: 6/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2029.26it/s, loss=247.2909, batch_time=0.032s]

Epoch: 7/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2125.44it/s, loss=232.3070, batch_time=0.030s]

Epoch: 8/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2107.30it/s, loss=218.3038, batch_time=0.030s]

Epoch: 9/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2162.51it/s, loss=209.3922, batch_time=0.030s]

Epoch: 10/10 - LR: 0.001000

100%|██████████| 1280/1280 [00:00<00:00, 2010.04it/s, loss=198.8523, batch_time=0.032s]

Finished training student cohort!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [0, 1] with losses: [tensor(526.6420, grad_fn=<MseLossBackward0>), tensor(40163.7109, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 271.0030822753906
Method: (weighted_average), Test_MSE: 270.8887939453125
Method: (greedy_ensemble), Test_MSE: 319.1759033203125
Method: (best_single), Test_MSE: 473.043212890625
Method: (cohort), Test_MSE: [473.043212890625, 530.6926879882812, 495.6028137207031]
Finished running joint fusion!
Start training student cohort...

Epoch: 1/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1428.65it/s, avg_loss=472.6379, batch_time=0.045s]

Epoch: 2/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1410.12it/s, avg_loss=406.9023, batch_time=0.045s]

Epoch: 3/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1404.17it/s, avg_loss=354.7575, batch_time=0.046s]

Epoch: 4/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1455.48it/s, avg_loss=324.5657, batch_time=0.044s]

Epoch: 5/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1410.02it/s, avg_loss=305.6218, batch_time=0.045s]

Epoch: 6/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1310.29it/s, avg_loss=288.9763, batch_time=0.049s]

Epoch: 7/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1488.86it/s, avg_loss=275.6041, batch_time=0.043s]

Epoch: 8/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1469.14it/s, avg_loss=263.3912, batch_time=0.044s]

Epoch: 9/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1425.61it/s, avg_loss=249.5422, batch_time=0.045s]

Epoch: 10/10 - LR: 0.001000
Using exact Shapley computation

100%|██████████| 1280/1280 [00:00<00:00, 1436.58it/s, avg_loss=236.2235, batch_time=0.045s]
Repetitions: 100%|██████████| 1/1 [00:23<00:00, 23.80s/it]

Finished training student cohort!
Selecting greedy ensemble on the best cohort...
Pruned 1 worst models, keeping 2 models
Initial best models: [1, 0] with losses: [tensor(445.2227, grad_fn=<MseLossBackward0>), tensor(464.6771, grad_fn=<MseLossBackward0>)]
Done!
Method: (simple_average), Test_MSE: 288.4032287597656
Method: (weighted_average), Test_MSE: 282.1300354003906
Method: (greedy_ensemble), Test_MSE: 306.8833312988281
Method: (best_single), Test_MSE: 333.8660888671875
Method: (cohort), Test_MSE: [434.3639831542969, 332.5388488769531, 347.43487548828125]
Finished running shapley fusion!

,Method,Test_metric,best_rho,cohort_pairs,ensemble_idxs,cluster_idxs,random_state,dim_modalities,n,n_train,n_val,n_test,extractor,weight_type
0,modality_1,393.490601,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
1,modality_2,369.784821,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
2,modality_3,377.919128,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
3,early_fusion,282.359131,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
4,late_fusion,331.14917,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
5,metafusion_simple_average,326.05423,0.99,"[200, 300, 100]",None,[1],1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
6,metafusion_weighted_average,324.052032,0.99,"[200, 300, 100]",None,[1],1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
7,metafusion_greedy_ensemble,318.82843,0.99,"[200, 300, 100]","[1, 2]",[1],1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
8,metafusion_best_single,358.433136,0.99,"[200, 300, 100]",None,[1],1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
9,metafusion_cohort,"[390.05145263671875, 358.4331359863281, 365.56...",0.99,"[200, 300, 100]",None,[1],1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
10,indep_simple_average,334.295074,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
11,indep_weighted_average,333.400146,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
12,indep_greedy_ensemble,328.522614,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
13,indep_best_single,378.646606,NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
14,indep_cohort,"[393.0150451660156, 378.6466064453125, 373.924...",NaN,"[200, 300, 100]",None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
15,jointlearning_simple_average,271.003082,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
16,jointlearning_weighted_average,270.888794,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
17,jointlearning_greedy_ensemble,319.175903,NaN,None,"[0, 1]",None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
18,jointlearning_best_single,473.043213,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
19,jointlearning_cohort,"[473.043212890625, 530.6926879882812, 495.6028...",NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
20,shapley_simple_average,288.403229,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
21,shapley_weighted_average,282.130035,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
22,shapley_greedy_ensemble,306.883331,NaN,None,"[1, 0]",None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
23,shapley_best_single,333.866089,NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering
24,shapley_cohort,"[434.3639831542969, 332.5388488769531, 347.434...",NaN,None,None,None,1234,"[200, 300, 100]",2000,1280,320,400,separate,clustering

In [5]:
EXPERIMENT_VARIANT = "filtered"

# Build a filename that encodes the key experiment parameters
outfile_name = (
    f"{EXPERIMENT_VARIANT}_"
    f"dim_modalities{dim_modalities}_"
    f"noise{noise_ratios}_"
    f"trans{trans_label}_"
    f"fractions{fractions}_"
    f"seed{seed}"
)
# sanitize characters that are annoying in filenames
outfile_name = (
    outfile_name.replace(" ", "")
    .replace("[", "(")
    .replace("]", ")")
    .replace(",", "-")
)

outfile = outdir + outfile_name + ".txt"
print("Output file: {:s}".format(outfile), end="\n")
sys.stdout.flush()


#####################
#    Save Results   #
#####################
results.to_csv(outfile, index=False)
print("\nResults written to {:s}\n".format(outfile))
sys.stdout.flush()

# After the job is done, remove the model directory to free up space
if os.path.exists(ckpt_dir):
    print(f"Deleting the model checkpoint directory: {ckpt_dir}")
    shutil.rmtree(ckpt_dir)
    print(f"Model checkpoint directory {ckpt_dir} has been deleted.")

Output file: ./results/regression_linear_early/filtered_dim_modalities(200-300-100)_noise(0.6-0.1-0.1)_transm1linear_m2quadratic_m3quadratic_sharedlinear_fractions(1-0.8-0.6)_seed1234.txt

Results written to ./results/regression_linear_early/filtered_dim_modalities(200-300-100)_noise(0.6-0.1-0.1)_transm1linear_m2quadratic_m3quadratic_sharedlinear_fractions(1-0.8-0.6)_seed1234.txt

Deleting the model checkpoint directory: ./checkpoints/regression_linear_early/seed1234/
Model checkpoint directory ./checkpoints/regression_linear_early/seed1234/ has been deleted.